// <auto-generated />
using System;
using KennisbeursGrimbergen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KennisbeursGrimbergen.Migrations
{
    [DbContext(typeof(KGContext))]
    [Migration("20220619191852_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KennisbeursGrimbergen.Entities.Activity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Animator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Animator = "Francis Aelbers",
                            Date = "donderdag 07/07/2022	14 - 16.30",
                            Description = "",
                            Email = "f.aelbers@scarlet.be",
                            Location = "Dienstencentrum Ter Borre",
                            Title = "Activiteit Bridge (samenwerking Ter Borre)",
                            UserId = 2L
                        },
                        new
                        {
                            Id = 2L,
                            Animator = "Edwin Van Geert",
                            Date = "Maandag 07/09/2022	14 - 16.30",
                            Description = "",
                            Email = "edwin.van.geert@skynet.be",
                            Location = "Dienstencentrum Ter Borre",
                            Title = "Activiteit Lezingen",
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Animator = "Ivan Van Malderen",
                            Date = "Vrijdag 27/07/2022	14 - 16.30",
                            Description = "",
                            Email = "ivan.van.malderen@telenet.be",
                            Location = "Dienstencentrum Ter Borre",
                            Title = "Activiteit Schaken",
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("KennisbeursGrimbergen.Entities.Translation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Key = "Welcome",
                            Language = "nl",
                            Value = "Welkom"
                        },
                        new
                        {
                            Id = 2L,
                            Key = "Welcome",
                            Language = "fr",
                            Value = "Bienvenue"
                        },
                        new
                        {
                            Id = 3L,
                            Key = "Welcome",
                            Language = "en",
                            Value = "Welcome"
                        },
                        new
                        {
                            Id = 4L,
                            Key = "Username",
                            Language = "nl",
                            Value = "Gebruikersnaam"
                        },
                        new
                        {
                            Id = 5L,
                            Key = "Username",
                            Language = "fr",
                            Value = "Nom d'utilisateur"
                        },
                        new
                        {
                            Id = 6L,
                            Key = "Username",
                            Language = "en",
                            Value = "Username"
                        },
                        new
                        {
                            Id = 7L,
                            Key = "Email",
                            Language = "nl",
                            Value = "E-mail"
                        },
                        new
                        {
                            Id = 8L,
                            Key = "E-mail",
                            Language = "fr",
                            Value = "E-mail"
                        },
                        new
                        {
                            Id = 9L,
                            Key = "Email",
                            Language = "en",
                            Value = "Email"
                        },
                        new
                        {
                            Id = 10L,
                            Key = "Password",
                            Language = "nl",
                            Value = "Wachtwoord"
                        },
                        new
                        {
                            Id = 11L,
                            Key = "Password",
                            Language = "fr",
                            Value = "Mot de passe"
                        },
                        new
                        {
                            Id = 12L,
                            Key = "Password",
                            Language = "en",
                            Value = "Password"
                        },
                        new
                        {
                            Id = 13L,
                            Key = "Register",
                            Language = "nl",
                            Value = "Registreren"
                        },
                        new
                        {
                            Id = 14L,
                            Key = "Register",
                            Language = "fr",
                            Value = "S'inscrire"
                        },
                        new
                        {
                            Id = 15L,
                            Key = "Register",
                            Language = "en",
                            Value = "Register"
                        },
                        new
                        {
                            Id = 16L,
                            Key = "A user already exist with the same email address.",
                            Language = "nl",
                            Value = "Er bestaat al een gebruiker met hetzelfde e-mailadres."
                        },
                        new
                        {
                            Id = 17L,
                            Key = "A user already exist with the same email address.",
                            Language = "fr",
                            Value = "Un utilisateur existe déjà avec la même adresse e-mail."
                        },
                        new
                        {
                            Id = 18L,
                            Key = "A user already exist with the same email address.",
                            Language = "en",
                            Value = "A user already exist with the same email address."
                        },
                        new
                        {
                            Id = 19L,
                            Key = "Registration sent for approval.",
                            Language = "nl",
                            Value = "Registratie verzonden en in afwachting op goedkeuring."
                        },
                        new
                        {
                            Id = 20L,
                            Key = "Registration sent for approval.",
                            Language = "fr",
                            Value = "Inscription envoyée pour approbation."
                        },
                        new
                        {
                            Id = 21L,
                            Key = "Registration sent for approval.",
                            Language = "en",
                            Value = "Registration sent for approval."
                        },
                        new
                        {
                            Id = 22L,
                            Key = "Registration failed",
                            Language = "nl",
                            Value = "Registratie mislukt"
                        },
                        new
                        {
                            Id = 23L,
                            Key = "Registration failed",
                            Language = "fr",
                            Value = "Échec de l'enregistrement"
                        },
                        new
                        {
                            Id = 24L,
                            Key = "Registration failed",
                            Language = "en",
                            Value = "Registration failed"
                        },
                        new
                        {
                            Id = 25L,
                            Key = "User not found.",
                            Language = "nl",
                            Value = "Gebruiker niet gevonden."
                        },
                        new
                        {
                            Id = 26L,
                            Key = "User not found.",
                            Language = "fr",
                            Value = "Utilisateur non trouvé."
                        },
                        new
                        {
                            Id = 27L,
                            Key = "User not found.",
                            Language = "en",
                            Value = "User not found."
                        },
                        new
                        {
                            Id = 28L,
                            Key = "User registration still processing..",
                            Language = "nl",
                            Value = "Gebruikersregistratie wordt nog verwerkt.."
                        },
                        new
                        {
                            Id = 29L,
                            Key = "User registration still processing..",
                            Language = "fr",
                            Value = "L'enregistrement de l'utilisateur est toujours en cours.."
                        },
                        new
                        {
                            Id = 30L,
                            Key = "User registration still processing..",
                            Language = "en",
                            Value = "User registration still processing.."
                        },
                        new
                        {
                            Id = 31L,
                            Key = "Login failed, make sure to provide the right credentials.",
                            Language = "nl",
                            Value = "Inloggen mislukt, zorg ervoor dat u de juiste inloggegevens opgeeft."
                        },
                        new
                        {
                            Id = 32L,
                            Key = "Login failed, make sure to provide the right credentials.",
                            Language = "fr",
                            Value = "La connexion a échoué, assurez-vous de fournir les bons identifiants."
                        },
                        new
                        {
                            Id = 33L,
                            Key = "Login failed, make sure to provide the right credentials.",
                            Language = "en",
                            Value = "Login failed, make sure to provide the right credentials."
                        },
                        new
                        {
                            Id = 34L,
                            Key = "Sign in",
                            Language = "nl",
                            Value = "Log in"
                        },
                        new
                        {
                            Id = 35L,
                            Key = "Sign in",
                            Language = "fr",
                            Value = "S'identifier"
                        },
                        new
                        {
                            Id = 36L,
                            Key = "Sign in",
                            Language = "en",
                            Value = "Sign in"
                        },
                        new
                        {
                            Id = 37L,
                            Key = "Home",
                            Language = "nl",
                            Value = "Home"
                        },
                        new
                        {
                            Id = 38L,
                            Key = "Home",
                            Language = "fr",
                            Value = "Accueil"
                        },
                        new
                        {
                            Id = 39L,
                            Key = "Home",
                            Language = "en",
                            Value = "Home"
                        },
                        new
                        {
                            Id = 40L,
                            Key = "Manage Users",
                            Language = "nl",
                            Value = "Gebruikers Beheren"
                        },
                        new
                        {
                            Id = 41L,
                            Key = "Manage Users",
                            Language = "fr",
                            Value = "Gérer Les Utilisateurs"
                        },
                        new
                        {
                            Id = 42L,
                            Key = "Manage Users",
                            Language = "en",
                            Value = "Manage Users"
                        },
                        new
                        {
                            Id = 43L,
                            Key = "English",
                            Language = "nl",
                            Value = "Engels"
                        },
                        new
                        {
                            Id = 44L,
                            Key = "English",
                            Language = "fr",
                            Value = "Anglais"
                        },
                        new
                        {
                            Id = 45L,
                            Key = "English",
                            Language = "en",
                            Value = "English"
                        },
                        new
                        {
                            Id = 46L,
                            Key = "Dutch",
                            Language = "nl",
                            Value = "Nederlands"
                        },
                        new
                        {
                            Id = 47L,
                            Key = "Dutch",
                            Language = "fr",
                            Value = "Néerlandais"
                        },
                        new
                        {
                            Id = 48L,
                            Key = "Dutch",
                            Language = "en",
                            Value = "Dutch"
                        },
                        new
                        {
                            Id = 49L,
                            Key = "French",
                            Language = "nl",
                            Value = "Frans"
                        },
                        new
                        {
                            Id = 50L,
                            Key = "French",
                            Language = "fr",
                            Value = "Français"
                        },
                        new
                        {
                            Id = 51L,
                            Key = "French",
                            Language = "en",
                            Value = "French"
                        },
                        new
                        {
                            Id = 52L,
                            Key = "Logout",
                            Language = "nl",
                            Value = "Uitloggen"
                        },
                        new
                        {
                            Id = 53L,
                            Key = "Logout",
                            Language = "fr",
                            Value = "Se déconnecter"
                        },
                        new
                        {
                            Id = 54L,
                            Key = "Logout",
                            Language = "en",
                            Value = "Logout"
                        },
                        new
                        {
                            Id = 55L,
                            Key = "Passwords must have at least one non alphanumeric character.",
                            Language = "nl",
                            Value = "Wachtwoorden moeten ten minste één niet-alfanumeriek teken bevatten."
                        },
                        new
                        {
                            Id = 56L,
                            Key = "Passwords must have at least one non alphanumeric character.",
                            Language = "fr",
                            Value = "Les mots de passe doivent comporter au moins un caractère non alphanumérique."
                        },
                        new
                        {
                            Id = 57L,
                            Key = "Passwords must have at least one non alphanumeric character.",
                            Language = "en",
                            Value = "Passwords must have at least one non alphanumeric character."
                        },
                        new
                        {
                            Id = 58L,
                            Key = "Approve",
                            Language = "nl",
                            Value = "Goedkeuren"
                        },
                        new
                        {
                            Id = 59L,
                            Key = "Approve",
                            Language = "fr",
                            Value = "Approuver"
                        },
                        new
                        {
                            Id = 60L,
                            Key = "Approve",
                            Language = "en",
                            Value = "Approve"
                        },
                        new
                        {
                            Id = 61L,
                            Key = "Reject",
                            Language = "nl",
                            Value = "Afwijzen"
                        },
                        new
                        {
                            Id = 62L,
                            Key = "Reject",
                            Language = "fr",
                            Value = "Rejeter"
                        },
                        new
                        {
                            Id = 63L,
                            Key = "Reject",
                            Language = "en",
                            Value = "Reject"
                        },
                        new
                        {
                            Id = 64L,
                            Key = "User has been approved.",
                            Language = "nl",
                            Value = "Gebruiker is goedgekeurd."
                        },
                        new
                        {
                            Id = 65L,
                            Key = "User has been approved.",
                            Language = "fr",
                            Value = "L'utilisateur a été approuvé."
                        },
                        new
                        {
                            Id = 66L,
                            Key = "User has been approved.",
                            Language = "en",
                            Value = "User has been approved."
                        },
                        new
                        {
                            Id = 67L,
                            Key = "Failed to approve user.",
                            Language = "nl",
                            Value = "Kan gebruiker niet goedkeuren."
                        },
                        new
                        {
                            Id = 68L,
                            Key = "Failed to approve user.",
                            Language = "fr",
                            Value = "Échec de l'approbation de l'utilisateur."
                        },
                        new
                        {
                            Id = 69L,
                            Key = "Failed to approve user.",
                            Language = "en",
                            Value = "Failed to approve user."
                        },
                        new
                        {
                            Id = 70L,
                            Key = "User has been rejected.",
                            Language = "nl",
                            Value = "Gebruiker is afgewezen."
                        },
                        new
                        {
                            Id = 71L,
                            Key = "User has been rejected.",
                            Language = "fr",
                            Value = "L'utilisateur a été rejeté."
                        },
                        new
                        {
                            Id = 72L,
                            Key = "User has been rejected.",
                            Language = "en",
                            Value = "User has been rejected."
                        },
                        new
                        {
                            Id = 73L,
                            Key = "Failed to reject user.",
                            Language = "nl",
                            Value = "Kan gebruiker niet weigeren."
                        },
                        new
                        {
                            Id = 74L,
                            Key = "Failed to reject user.",
                            Language = "fr",
                            Value = "Échec du rejet de l'utilisateur."
                        },
                        new
                        {
                            Id = 75L,
                            Key = "Failed to reject user.",
                            Language = "en",
                            Value = "Failed to approve user."
                        },
                        new
                        {
                            Id = 76L,
                            Key = "Manager Dashboard",
                            Language = "nl",
                            Value = "Beheerdersdashboard"
                        },
                        new
                        {
                            Id = 77L,
                            Key = "Manager Dashboard",
                            Language = "fr",
                            Value = "Tableau de bord du gestionnaire"
                        },
                        new
                        {
                            Id = 78L,
                            Key = "Manager Dashboard",
                            Language = "en",
                            Value = "Manager Dashboard"
                        },
                        new
                        {
                            Id = 79L,
                            Key = "Approve new users and/or set permissions.",
                            Language = "nl",
                            Value = "Nieuwe gebruikers goedkeuren en/of machtigingen instellen."
                        },
                        new
                        {
                            Id = 80L,
                            Key = "Approve new users and/or set permissions.",
                            Language = "fr",
                            Value = "Approuver de nouveaux utilisateurs et/ou définir des autorisations."
                        },
                        new
                        {
                            Id = 81L,
                            Key = "Approve new users and/or set permissions.",
                            Language = "en",
                            Value = "Approve new users and/or set permissions."
                        },
                        new
                        {
                            Id = 82L,
                            Key = "Permissions",
                            Language = "nl",
                            Value = "Rechten"
                        },
                        new
                        {
                            Id = 83L,
                            Key = "Permissions",
                            Language = "fr",
                            Value = "Autorisations"
                        },
                        new
                        {
                            Id = 84L,
                            Key = "Permissions",
                            Language = "en",
                            Value = "Permissions"
                        },
                        new
                        {
                            Id = 85L,
                            Key = "Approved",
                            Language = "nl",
                            Value = "Goedgekeurd"
                        },
                        new
                        {
                            Id = 86L,
                            Key = "Approved",
                            Language = "fr",
                            Value = "Approuvée"
                        },
                        new
                        {
                            Id = 87L,
                            Key = "Approved",
                            Language = "en",
                            Value = "Approved"
                        },
                        new
                        {
                            Id = 88L,
                            Key = "User",
                            Language = "nl",
                            Value = "Gebruiker"
                        },
                        new
                        {
                            Id = 89L,
                            Key = "User",
                            Language = "fr",
                            Value = "Utilisateur/Utilisatrice"
                        },
                        new
                        {
                            Id = 90L,
                            Key = "User",
                            Language = "en",
                            Value = "User"
                        },
                        new
                        {
                            Id = 91L,
                            Key = "Manager",
                            Language = "nl",
                            Value = "Beheerder"
                        },
                        new
                        {
                            Id = 92L,
                            Key = "Manager",
                            Language = "fr",
                            Value = "Gestionnaire"
                        },
                        new
                        {
                            Id = 93L,
                            Key = "Manager",
                            Language = "en",
                            Value = "Manager"
                        },
                        new
                        {
                            Id = 94L,
                            Key = "Admin",
                            Language = "nl",
                            Value = "Admin"
                        },
                        new
                        {
                            Id = 95L,
                            Key = "Admin",
                            Language = "fr",
                            Value = "Admin"
                        },
                        new
                        {
                            Id = 96L,
                            Key = "Admin",
                            Language = "en",
                            Value = "Admin"
                        },
                        new
                        {
                            Id = 97L,
                            Key = "Update",
                            Language = "nl",
                            Value = "Update"
                        },
                        new
                        {
                            Id = 98L,
                            Key = "Update",
                            Language = "fr",
                            Value = "Modifier"
                        },
                        new
                        {
                            Id = 99L,
                            Key = "Update",
                            Language = "en",
                            Value = "Update"
                        },
                        new
                        {
                            Id = 100L,
                            Key = "User's permissions has been updated.",
                            Language = "nl",
                            Value = "De machtigingen van de gebruiker zijn bijgewerkt."
                        },
                        new
                        {
                            Id = 101L,
                            Key = "User's permissions has been updated.",
                            Language = "fr",
                            Value = "Les autorisations de l'utilisateur ont été mises à jour."
                        },
                        new
                        {
                            Id = 102L,
                            Key = "User's permissions has been updated.",
                            Language = "en",
                            Value = "User's permissions has been updated."
                        },
                        new
                        {
                            Id = 103L,
                            Key = "Failed to update user's permissions.",
                            Language = "nl",
                            Value = "Kan gebruikersrechten niet updaten."
                        },
                        new
                        {
                            Id = 104L,
                            Key = "Failed to update user's permissions.",
                            Language = "fr",
                            Value = "Échec de la mise à jour des autorisations de l'utilisateur."
                        },
                        new
                        {
                            Id = 105L,
                            Key = "Failed to update user's permissions.",
                            Language = "en",
                            Value = "Update"
                        },
                        new
                        {
                            Id = 106L,
                            Key = "User (Read Only)",
                            Language = "nl",
                            Value = "Gebruiker (Read Only)"
                        },
                        new
                        {
                            Id = 107L,
                            Key = "User (Read Only)",
                            Language = "fr",
                            Value = "Utilisateur/Utilisatrice (lecture seule)"
                        },
                        new
                        {
                            Id = 108L,
                            Key = "User (Read Only)",
                            Language = "en",
                            Value = "User (Read Only)"
                        },
                        new
                        {
                            Id = 109L,
                            Key = "Cancel",
                            Language = "nl",
                            Value = "Annuleren"
                        },
                        new
                        {
                            Id = 110L,
                            Key = "Cancel",
                            Language = "fr",
                            Value = "Annuler"
                        },
                        new
                        {
                            Id = 111L,
                            Key = "Cancel",
                            Language = "en",
                            Value = "Cancel"
                        },
                        new
                        {
                            Id = 112L,
                            Key = "Objectives",
                            Language = "nl",
                            Value = "Doelstellingen"
                        },
                        new
                        {
                            Id = 113L,
                            Key = "Objectives",
                            Language = "fr",
                            Value = "Objectifs"
                        },
                        new
                        {
                            Id = 114L,
                            Key = "Objectives",
                            Language = "en",
                            Value = "Objectives"
                        },
                        new
                        {
                            Id = 115L,
                            Key = "Management",
                            Language = "nl",
                            Value = "Bestuur"
                        },
                        new
                        {
                            Id = 116L,
                            Key = "Management",
                            Language = "fr",
                            Value = "Gestion"
                        },
                        new
                        {
                            Id = 117L,
                            Key = "Management",
                            Language = "en",
                            Value = "Management"
                        },
                        new
                        {
                            Id = 118L,
                            Key = "Activities",
                            Language = "nl",
                            Value = "Activiteiten"
                        },
                        new
                        {
                            Id = 119L,
                            Key = "Activities",
                            Language = "fr",
                            Value = "Activités"
                        },
                        new
                        {
                            Id = 120L,
                            Key = "Activities",
                            Language = "en",
                            Value = "Activities"
                        },
                        new
                        {
                            Id = 121L,
                            Key = "Links",
                            Language = "nl",
                            Value = "Links"
                        },
                        new
                        {
                            Id = 122L,
                            Key = "Links",
                            Language = "fr",
                            Value = "Liens"
                        },
                        new
                        {
                            Id = 123L,
                            Key = "Links",
                            Language = "en",
                            Value = "Links"
                        },
                        new
                        {
                            Id = 124L,
                            Key = "Objectives and method",
                            Language = "nl",
                            Value = "Doelstellingen en werkwijze"
                        },
                        new
                        {
                            Id = 125L,
                            Key = "Objectives and method",
                            Language = "fr",
                            Value = "Objectifs et méthode"
                        },
                        new
                        {
                            Id = 126L,
                            Key = "Objectives and method",
                            Language = "en",
                            Value = "Objectives and method"
                        },
                        new
                        {
                            Id = 127L,
                            Key = "Anyone who leaves active professional life does so with a lot of knowledge and skills. The aim of the Knowledge Exchange is to exchange this: to pass on what one knows to others and to capture interesting knowledge or skills from those others. There is also ample opportunity to build up new social contacts after the cessation of professional activities.",
                            Language = "nl",
                            Value = "Iedereen die uit het actieve beroepsleven stapt doet dit met een pak kennis en vaardigheden. Het is de bedoeling van de Kennisbeurs om dit uit te wisselen : wat men weet doorgeven aan anderen en van die anderen interessante kennis of kunde capteren. Er wordt ook ruimschoots de mogelijkheid geboden om nieuwe sociale contacten op te bouwen na het wegvallen van de beroepsactiviteiten."
                        },
                        new
                        {
                            Id = 128L,
                            Key = "Anyone who leaves active professional life does so with a lot of knowledge and skills. The aim of the Knowledge Exchange is to exchange this: to pass on what one knows to others and to capture interesting knowledge or skills from those others. There is also ample opportunity to build up new social contacts after the cessation of professional activities.",
                            Language = "fr",
                            Value = "Quiconque quitte la vie professionnelle active le fait avec beaucoup de connaissances et de compétences. Le but de l'échange de connaissances est d'échanger cela : transmettre ce que l'on sait à d'autres et capter des connaissances ou des compétences intéressantes de ces autres. Il existe également de nombreuses possibilités de nouer de nouveaux contacts sociaux après la cessation des activités professionnelles."
                        },
                        new
                        {
                            Id = 129L,
                            Key = "Anyone who leaves active professional life does so with a lot of knowledge and skills. The aim of the Knowledge Exchange is to exchange this: to pass on what one knows to others and to capture interesting knowledge or skills from those others. There is also ample opportunity to build up new social contacts after the cessation of professional activities.",
                            Language = "en",
                            Value = "Anyone who leaves active professional life does so with a lot of knowledge and skills. The aim of the Knowledge Exchange is to exchange this: to pass on what one knows to others and to capture interesting knowledge or skills from those others. There is also ample opportunity to build up new social contacts after the cessation of professional activities."
                        },
                        new
                        {
                            Id = 130L,
                            Key = "Our motto is therefore",
                            Language = "nl",
                            Value = "Ons motto is dan ook"
                        },
                        new
                        {
                            Id = 131L,
                            Key = "Our motto is therefore",
                            Language = "fr",
                            Value = "Notre devise est donc"
                        },
                        new
                        {
                            Id = 132L,
                            Key = "Our motto is therefore",
                            Language = "en",
                            Value = "Our motto is therefore"
                        },
                        new
                        {
                            Id = 133L,
                            Key = "Giving Knowledge, Taking Knowledge and Making Acquaintances.",
                            Language = "nl",
                            Value = "Kennis geven, Kennis nemen en Kennissen maken."
                        },
                        new
                        {
                            Id = 134L,
                            Key = "Giving Knowledge, Taking Knowledge and Making Acquaintances.",
                            Language = "fr",
                            Value = "Donner des connaissances, prendre des connaissances et faire des connaissances."
                        },
                        new
                        {
                            Id = 135L,
                            Key = "Giving Knowledge, Taking Knowledge and Making Acquaintances.",
                            Language = "en",
                            Value = "Giving Knowledge, Taking Knowledge and Making Acquaintances."
                        },
                        new
                        {
                            Id = 136L,
                            Key = "Apart from the lectures, the activities take place in small groups, so that everyone can participate actively. Each group is led by an animator who convenes the participants, supervises and takes care of the facilities. The program is largely determined by the members themselves. Success therefore depends not only on the animators but also on the participants, who are expected to make an active contribution. If a group becomes too numerous, it is split up. This ensures that everyone is covered.",
                            Language = "nl",
                            Value = "De lezingen niet te na gesproken, gebeuren de activiteiten in kleine groepen, zodat iedereen actief kan deelnemen. Elke groep staat onder de leiding van een animator die de deelnemers bijeenroept, begeleidt en zorgt voor de faciliteiten. Het programma bepalen de leden in grote mate zelf. Het welslagen hangt dus niet alleen af van de animatoren maar ook van de deelnemers, waarvan verwacht wordt dat ze een actieve inbreng leveren. Wordt een groep te talrijk, dan wordt overgegaan tot splitsing ervan. Aldus zorgt men ervoor dat elkeen aan bod komt."
                        },
                        new
                        {
                            Id = 137L,
                            Key = "Apart from the lectures, the activities take place in small groups, so that everyone can participate actively. Each group is led by an animator who convenes the participants, supervises and takes care of the facilities. The program is largely determined by the members themselves. Success therefore depends not only on the animators but also on the participants, who are expected to make an active contribution. If a group becomes too numerous, it is split up. This ensures that everyone is covered.",
                            Language = "fr",
                            Value = "En dehors des conférences, les activités se déroulent en petits groupes, afin que chacun puisse participer activement. Chaque groupe est animé par un animateur qui convoque les participants, encadre et entretient les installations. Le programme est largement déterminé par les membres eux-mêmes. Le succès dépend donc non seulement des animateurs mais aussi des participants, dont on attend une contribution active. Si un groupe devient trop nombreux, il est divisé. Cela garantit que tout le monde est couvert."
                        },
                        new
                        {
                            Id = 138L,
                            Key = "Apart from the lectures, the activities take place in small groups, so that everyone can participate actively. Each group is led by an animator who convenes the participants, supervises and takes care of the facilities. The program is largely determined by the members themselves. Success therefore depends not only on the animators but also on the participants, who are expected to make an active contribution. If a group becomes too numerous, it is split up. This ensures that everyone is covered.",
                            Language = "en",
                            Value = "Apart from the lectures, the activities take place in small groups, so that everyone can participate actively. Each group is led by an animator who convenes the participants, supervises and takes care of the facilities. The program is largely determined by the members themselves. Success therefore depends not only on the animators but also on the participants, who are expected to make an active contribution. If a group becomes too numerous, it is split up. This ensures that everyone is covered."
                        },
                        new
                        {
                            Id = 139L,
                            Key = "Sister Associations",
                            Language = "nl",
                            Value = "Zusterverenigingen"
                        },
                        new
                        {
                            Id = 140L,
                            Key = "Sister Associations",
                            Language = "fr",
                            Value = "Associations Sœurs"
                        },
                        new
                        {
                            Id = 141L,
                            Key = "Sister Associations",
                            Language = "en",
                            Value = "Sister Associations"
                        },
                        new
                        {
                            Id = 142L,
                            Key = "Executive Committee",
                            Language = "nl",
                            Value = "Zusterverenigingen"
                        },
                        new
                        {
                            Id = 143L,
                            Key = "Executive Committee",
                            Language = "fr",
                            Value = "Associations Sœurs"
                        },
                        new
                        {
                            Id = 144L,
                            Key = "Executive Committee",
                            Language = "en",
                            Value = "Executive Committee"
                        },
                        new
                        {
                            Id = 145L,
                            Key = "Function",
                            Language = "nl",
                            Value = "Functie"
                        },
                        new
                        {
                            Id = 146L,
                            Key = "Function",
                            Language = "fr",
                            Value = "Fonction"
                        },
                        new
                        {
                            Id = 147L,
                            Key = "Function",
                            Language = "en",
                            Value = "Function"
                        },
                        new
                        {
                            Id = 148L,
                            Key = "Information",
                            Language = "nl",
                            Value = "Informatie"
                        },
                        new
                        {
                            Id = 149L,
                            Key = "Information",
                            Language = "fr",
                            Value = "Information"
                        },
                        new
                        {
                            Id = 150L,
                            Key = "Information",
                            Language = "en",
                            Value = "Information"
                        },
                        new
                        {
                            Id = 151L,
                            Key = "Chair",
                            Language = "nl",
                            Value = "Voorzitter"
                        },
                        new
                        {
                            Id = 152L,
                            Key = "Chair",
                            Language = "fr",
                            Value = "Président"
                        },
                        new
                        {
                            Id = 153L,
                            Key = "Chair",
                            Language = "en",
                            Value = "Chair"
                        },
                        new
                        {
                            Id = 154L,
                            Key = "Secretary",
                            Language = "nl",
                            Value = "Secretaris"
                        },
                        new
                        {
                            Id = 155L,
                            Key = "Secretary",
                            Language = "fr",
                            Value = "Secrétaire"
                        },
                        new
                        {
                            Id = 156L,
                            Key = "Secretary",
                            Language = "en",
                            Value = "Secretary"
                        },
                        new
                        {
                            Id = 157L,
                            Key = "Treasurer",
                            Language = "nl",
                            Value = "Penningmeester"
                        },
                        new
                        {
                            Id = 158L,
                            Key = "Treasurer",
                            Language = "fr",
                            Value = "Trésorière/Trésorier"
                        },
                        new
                        {
                            Id = 159L,
                            Key = "Treasurer",
                            Language = "en",
                            Value = "Treasurer"
                        },
                        new
                        {
                            Id = 160L,
                            Key = "Send mail",
                            Language = "nl",
                            Value = "Verzend mail"
                        },
                        new
                        {
                            Id = 161L,
                            Key = "Send mail",
                            Language = "fr",
                            Value = "Envoyer un mail"
                        },
                        new
                        {
                            Id = 162L,
                            Key = "Send mail",
                            Language = "en",
                            Value = "Send mail"
                        },
                        new
                        {
                            Id = 163L,
                            Key = "Activity",
                            Language = "nl",
                            Value = "Activiteit"
                        },
                        new
                        {
                            Id = 164L,
                            Key = "Activity",
                            Language = "fr",
                            Value = "Activité"
                        },
                        new
                        {
                            Id = 165L,
                            Key = "Activity",
                            Language = "en",
                            Value = "Activity"
                        },
                        new
                        {
                            Id = 166L,
                            Key = "Title",
                            Language = "nl",
                            Value = "Titel"
                        },
                        new
                        {
                            Id = 167L,
                            Key = "Title",
                            Language = "fr",
                            Value = "Titre"
                        },
                        new
                        {
                            Id = 168L,
                            Key = "Title",
                            Language = "en",
                            Value = "Title"
                        },
                        new
                        {
                            Id = 169L,
                            Key = "Description",
                            Language = "nl",
                            Value = "Beschrijving"
                        },
                        new
                        {
                            Id = 170L,
                            Key = "Description",
                            Language = "fr",
                            Value = "Description"
                        },
                        new
                        {
                            Id = 171L,
                            Key = "Description",
                            Language = "en",
                            Value = "Description"
                        },
                        new
                        {
                            Id = 172L,
                            Key = "Animator",
                            Language = "nl",
                            Value = "Animator"
                        },
                        new
                        {
                            Id = 173L,
                            Key = "Animator",
                            Language = "fr",
                            Value = "Animateur"
                        },
                        new
                        {
                            Id = 174L,
                            Key = "Animator",
                            Language = "en",
                            Value = "Animator"
                        },
                        new
                        {
                            Id = 175L,
                            Key = "Date",
                            Language = "nl",
                            Value = "Datum"
                        },
                        new
                        {
                            Id = 176L,
                            Key = "Date",
                            Language = "fr",
                            Value = "Date"
                        },
                        new
                        {
                            Id = 177L,
                            Key = "Date",
                            Language = "en",
                            Value = "Date"
                        },
                        new
                        {
                            Id = 178L,
                            Key = "Location",
                            Language = "nl",
                            Value = "Plaats"
                        },
                        new
                        {
                            Id = 179L,
                            Key = "Location",
                            Language = "fr",
                            Value = "Lieu"
                        },
                        new
                        {
                            Id = 180L,
                            Key = "Location",
                            Language = "en",
                            Value = "Location"
                        },
                        new
                        {
                            Id = 181L,
                            Key = "Create",
                            Language = "nl",
                            Value = "Creëren"
                        },
                        new
                        {
                            Id = 182L,
                            Key = "Create",
                            Language = "fr",
                            Value = "Créer"
                        },
                        new
                        {
                            Id = 183L,
                            Key = "Create",
                            Language = "en",
                            Value = "Create"
                        },
                        new
                        {
                            Id = 184L,
                            Key = "Create new",
                            Language = "nl",
                            Value = "Maak nieuw"
                        },
                        new
                        {
                            Id = 185L,
                            Key = "Create new",
                            Language = "fr",
                            Value = "Créer une nouvelle"
                        },
                        new
                        {
                            Id = 186L,
                            Key = "Create new",
                            Language = "en",
                            Value = "Create new"
                        },
                        new
                        {
                            Id = 187L,
                            Key = "Read more..",
                            Language = "nl",
                            Value = "Lees verder.."
                        },
                        new
                        {
                            Id = 188L,
                            Key = "Read more..",
                            Language = "fr",
                            Value = "Lire la suite.."
                        },
                        new
                        {
                            Id = 189L,
                            Key = "Read more..",
                            Language = "en",
                            Value = "Read more.."
                        });
                });

            modelBuilder.Entity("KennisbeursGrimbergen.Identity.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("KennisbeursGrimbergen.Identity.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("KennisbeursGrimbergen.Identity.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("KennisbeursGrimbergen.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("KennisbeursGrimbergen.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("KennisbeursGrimbergen.Identity.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KennisbeursGrimbergen.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("KennisbeursGrimbergen.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
